### ISSUE TITLE
Question about Sonic sprites

### ISSUE THREAD

**Issue by MDTravisYT** [Ralakimus/sonic-cd-disassembly#3]
I've noticed between MMD files that certain Sonic sprites were excluded from the file (such as Collision Chaos lacking the spinning platform sprites). I'm curious about how you'll handle this, especially the sprites that weren't compiled into the final release ([these](https://i.imgur.com/NDwEpdu.png)). The 0.02 prototype and 1995 PC release doesn't do this and has all Sonic sprites compiled into each level.

**Comment by Ralakimus** [comment]
Anything uncompiled will be left out. Initially, I'll just have them separated out. If I can find a way to streamline it all, then I'll do that.
